### ISSUE TITLE
ADSL: get the code running

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/end_to_end_examples#8]
ADSL: https://github.com/pharmaverse/end_to_end_examples/blob/main/content/data/adsl/_index.Rmd

Currently fails since I removed a bunch of the vars that metacore has from the specs, so our suggestion is to create them as dummy vars with expected var types and then hide this code from appearing in the vignette. so it runs and still remains simple for the user view, and easy for us to maintain.

Also instead of `dataset_vignette()` just replace these bits with simpler tibbles or head calls to show a small extract of the dataset as we go through the steps.

**Comment by rossfarrugia** [comment]
@statasaurus @amitjaingsk please check my updates in the commit above and if you're happy then i think we can publish our first e2e vignette for ADSL - i can work with James to get this up on the pharmaverse site.

**Comment by amitjaingsk** [comment]
@rossfarrugia sorry for the late review, few of points if you think are relevant : 1. metacore can reads the specification in xlsx format, do we need to provide an example how it looks like or any constraint on how this file need to be created. Just trying to see if someone like to try on real data/specs using this example 2. build_from_derived , how it know which SDTM domain is needed? is this is fixed in some function? do it support multiple SDTM domains for we only intent to pass 1 SDTM domain. But overall this example looks fine to me not able to run it as getting some errors..

**Comment by rossfarrugia** [comment]
@statasaurus do you want to reply to Amit's questions above? i wouldn't do your packages justice.
